const fishingQuotes = [
  `“Many men go fishing all of their lives without knowing that it is not fish they are after,” - Henry David Thoreau.`,
  `“If people concentrated on the really important things in life, there’d be a shortage of fishing poles,” Doug Larson`,
  `“A bad day of fishing is still better than a good day at the office!” Author Unknown`,
  `“A woman, who has never seen her husband fishing, doesn’t know what a patient man she married!” Author Unknown`,
  `“Early to bed…early to rise…fish all day…make up lies,” Author Unknown`,
  `“Some people will just never understand us, fishing isn’t just a pass time or a sport, it’s a way of life. DON’T MESS WITH MY WAY OF LIFE!” Author Unknown`,
  `“The charm of fishing is that it is the pursuit of that which is elusive but attainable, a perpetual series of occasions for hope,” John Bucha`,
  `“To fish or not to fish? That’s a dumb question,” Author Unknown.`,
  `“I spent most of my money on fishing. The rest I wasted,” Author Unknown`,
  `“Life is like a game, but fishing is serious,” Author Unknown`,
  `“Give a man a fish; he will eat for a day. Teach a man to fish and you will find bait in the fridge,” Author Unknown`,
  `“Those who die with the most days fishing, wins,” Author Unknown`,
  `“Work is for people who don’t know how to fish!” Author Unknown`,
  `“Men and fish are alike. They both get into trouble when they open their mouths,” Author Unknown`,
  `“Fishing is the sport of drowning worms,” Author Unknown`,
  `“It has always been my private conviction that any man who pits his intelligence against a fish and loses has it coming.” John Steinbeck`,
  `“Bragging may not bring happiness, but no man having caught a large fish goes home through an alley,” Author Unknown`,
  `“Fishing is a discipline in the equality of men – for all men are equal before fish,” Author Unknown`,
  `“Good things come to those who bait,” Author Unknown`,
  `“Carpe Diem, does not mean fish of the day,” Author Unknown`,
  `“Nothing makes a fish bigger than almost being caught,” Author Unknown`,
  `“Soon after I embraced the sport of angling I became convinced that I should never be able to enjoy it if I had to rely on the cooperation of the fish,” Sparse Grey Hackle`,
  `“Angling is extremely time consuming. That’s sort of the whole point,” Thomas McGuane`,
  `“It is impossible to grow weary of a sport that is never the same on any two days of the year,” Theodore Gordon`,
  `“There will be days when the fishing is better than one’s most optimistic forecast, others when it is far worse. Either is a gain over just staying home,” Roderick Haig Brown`,
  `“The solution to any problem — work, love, money, whatever is to go fishing, and the worse the problem, the longer the trip should be,” John Gierach`,
  `“If fishing is interfering with your business, give up your business,” Sparse Grey Hackle`,
  `“Fishing is not an escape from life, but often a deeper immersion into it,” Harry Middleton`,
  `“I go fishing not to find myself but to lose myself,” Joseph Monniger`,
  `“There is only one reason in the world to go fishing: to enjoy yourself. Anything that detracts from enjoying yourself is to be avoided,” Leigh Perkins`,
  `Calling fishing a hobby is like calling brain surgery a job,” Paul Schullery`,
  `“Most of the world is covered by water. A fisherman’s job is simple: Pick out the best parts,” Charles Waterman`,
  `“Scholars have long known that fishing eventually turns men into philosophers. Unfortunately, it is almost impossible to buy decent tackle on a philosopher’s salary,” Patrick McManus`,
  `“Everyone should believe in something. I believe I’ll go fishing,” Henry David Thoreau`,
  `“You know when they have a fishing show on TV? They catch the fish and then let it go. They don’t want to eat the fish, they just want to make it late for something,” Mitch Hedberg`,
  `“There he stands, draped in more equipment than a telephone lineman, trying to outwit an organism with a brain no bigger than a breadcrumb, and getting licked in the process,” Paul O’Neil`,
  `“Always think like a fish, no matter how weird it gets,” Author Unknown`,
  `“I fish because the voice in my head tells me to,” Author Unknown`,
  `“I’m a man of few words, “Let’s fish,” Author Unknown`,
  `“Fishing is a discipline in the equality of men – for all men are equal before fish,” Herbert Hoover`,
  `"There's a fine line between fishing and just standing on the shore like an idiot." - Steven Wright`,
];

export default fishingQuotes